config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories, dependent: :destroy
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 5, maximum: 400 }
	validates :user_id, presence: true
end

app/models/article_category.rb
    
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :article_categories, dependent: :destroy
	has_many :articles, through: :article_categories
	validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 2, maximum: 30 }
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save {self.email = email.downcase}
  validates :username, presence: true, 
            uniqueness: {case_sensitive: false}, 
            length: {minimum:3, maximum:25}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            uniqueness: {case_sensitive: false}, 
            length: {maximum:105},
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    # If session[userId] is not empty, then try to find User object and set to current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # If the current user exists, then must be logged in
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must login to perform that action."
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	def index
		@order_articles = Article.order(updated_at: :desc)
		@articles = @order_articles.paginate(:page => params[:page], :per_page => 5)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
#logger = Logger.new('article_log.log')
		@article = Article.new(article_params)
		@article.user = current_user
#logger.debug "Article User Count is: #{User.count}"
#logger.debug "User LAST email is: #{@aUser.email}"
		if @article.save
			flash[:success] = "Article successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article successfully deleted"
		redirect_to articles_path
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description, category_ids: [])
		end

		def require_same_user
			if !logged_in? || (current_user != @article.user && !current_user.admin?)
				flash[:danger] = "You are not authorised to perform that action."
				redirect_to root_path
			end
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:show, :index]
	
	def index
		@categories = Category.paginate(:page => params[:page], :per_page => 8)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category successfully created"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def show
		@category = Category.find(params[:id])
		@category_articles = @category.articles.paginate(:page => params[:page], :per_page => 5)
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success] = "Category successfully updated"
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		flash[:danger] = "Category successfully deleted"
		redirect_to categories_path
	end

	private
		def category_params
			params.require(:category).permit(:name, :description)
		end

		def require_admin
			if !logged_in? || !current_user.admin?
				flash[:danger] = "You are not authorised to perform that action."
				redirect_to categories_path
			end
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?

  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "Login Successful"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "Invalid Email or Password entered."
			render 'new'
		end
	end
	def destroy
		session[:user_id] = nil
		flash[:success] = "You have successfully logged out."
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit,  :update, :show, :destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(:page => params[:page], :per_page => 5)
	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to Alpha Blog #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Account successfully updated"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(:page => params[:page], :per_page => 5)
	end

	def destroy
		@user =User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all associated Articles successfully deleted"
		redirect_to users_path
	end

	private
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end

		def set_user
			@user = User.find(params[:id])
		end

		def require_same_user
			if !logged_in? || (current_user != @user && !current_user.admin?)
				flash[:danger] = "You are not authorised to perform that action."
				redirect_to root_path
			end
		end

		def require_admin
			if !logged_in? || !current_user.admin?
				flash[:danger] = "You are not authorised to perform that action."
				redirect_to root_path
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
	end
end

app/views/articles/_article.html.erb
<% object.each do |article| %>
	<div class="card card-adjust">
		<div class="card-header card-list-header-adjust">
			<h4><%= link_to article.title, article_path(article) %></h4>
		</div>
		<div class="card-body">
			<div class="card-text card-list-text-adjust"><%= truncate(article.description, length: 100) %></div>
			<% if article.categories.any? %>
				<p>Categories: <%= render article.categories %></p>
			<% end %>
			<div class="center">
			<% if logged_in? && (current_user == article.user || current_user.admin?) %>
				<%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-sm btn-primary center" %>
				<%= link_to "Delete this Article", article_path(article), method: :delete, data: { confirm: "Are you sure you wish to Delete this Article?"}, class: "btn btn-sm btn-danger" %>
				</div>
			<% end %>
			<div class="article-times">
				<small>Created by: <%= article.user.username.gsub(/\w{2,}\b/) { |word| word.capitalize } if article.user %>, <%= time_ago_in_words(article.created_at) %> ago, Last Updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article, message: message_type, type: "article" %>

<%= form_for @article do |f| %>
	<div class="form-group row">
		<div class="col-form-label col-sm-2">
			<%= f.label :title %>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :title, class: "form-control", placeholder: "Article Title", autofocus: true %>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-form-label col-sm-2">
			<%= f.label :description %>
		</div>
		<div class="col-sm-8">
			<%= f.text_area :description, rows: 12, class: "form-control", placeholder: "Article Content" %>
		</div>
	</div>

	<div class="form-group form-inline">
		<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
			<div class="custom-control custom-checkbox my-1 mr-sm-2">
				<%= cb.check_box(class: "custom-control-input checkbox-box-adjust") %>
				<%= cb.label(class: "custom-control-label checkbox-label-adjust") %>
			</div>
		<% end %>
	</div>

	<div class="form-group row">
		<div class="col-sm-12 center">
			<%= f.submit class: "btn btn-primary btn-lg" %>
		</div>
	</div>
<% end %>
<p class="center"><%= link_to "Return to Article Listing", articles_path %></p>

app/views/articles/edit.html.erb
<br/><h1 class="center">Edit Existing Article</h1><hr/>

<%= render 'form', message_type: "edit" %>

app/views/articles/index.html.erb
<h1 class="action-heading center">All Articles</h1>
<div class="apple_pagination">
	<%= will_paginate @articles %>
</div>
<%= render 'article', object: @articles %>
<div class="apple_pagination">
	<%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1 class="center">Create a new article</h1><hr/>

<%= render 'form', message_type: "create" %>

app/views/articles/show.html.erb
<h2 class="action-heading">Title: <%= @article.title %></h2>

<div class="card card-adjust bg-light">
	<% if @article.user %>
		<div class="card-body text-center">
			<p>Created By:</p>
			<p><%= link_to gravatar_for(@article.user, size: 120), user_path(@article.user), class: "center" %></p>
			<h4><%= link_to @article.user.username.gsub(/\w{2,}\b/) { |word| word.capitalize }, user_path(@article.user), class: "center" %></h4>
		</div>
	<% end %>
	<div class="card-header card-shrink-top-margin">
		<h4>Description:</h4>
	</div>
	<div class="card-body">
		<div class="card-text"><%= simple_format(@article.description) %></div>
		<% if @article.categories.any? %>
			<p>Categories: <%= render @article.categories %></p>
		<% end %>
		<% if logged_in? && (current_user == @article.user || current_user.admin?) %> 
			<%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-sm btn-primary" %>
			<%= link_to "Delete this Article", article_path(@article), method: :delete, data: { confirm: "Are you sure you wish to Delete this Article?"}, class: "btn btn-sm btn-danger" %>
		<% end %>
	</div>
</div>
<div class="top-pad">
	<%= link_to "Return to Article Listing", articles_path %>	

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info badge-adjust badge-pill-adjust" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category, message: message_type, type: "category" %>

<%= form_for @category do |f| %>
	<div class="form-group row">
		<div class="col-form-label col-sm-2">
			<%= f.label :name %>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :name, class: "form-control", placeholder: "Category Name", autofocus: true %>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-form-label col-sm-2">
			<%= f.label :description %>
		</div>
		<div class="col-sm-8">
			<%= f.text_area :description, rows: 2, class: "form-control", placeholder: "Category Description" %>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-10">
			<%= f.submit class: "btn btn-primary btn-lg" %>
		</div>
	</div>
<% end %>
<p><%= link_to "Return to Category Listing", categories_path %></p>

app/views/categories/edit.html.erb
<h2 class="action-heading">Edit Category</h2>
<%= render 'form', message_type: "edit" %>

app/views/categories/index.html.erb
<h2 class="action-heading center">All Categories</h2>
<div class="apple_pagination">
	<%= will_paginate @categories %>
</div>
<% @categories.each do |category| %>
	<div class="card text-center card-adjust w-50 mx-auto">
		<div class="card-body">
			<h4><%= link_to category.name.gsub(/\w{2,}\b/) { |word| word.capitalize }, category_path(category), class: "center" %></h4>
			<div class="text-muted"><%= pluralize(category.articles.count, "article") if category.articles.any? %></div>
			<% if logged_in? && current_user.admin? %>
				<div class="center marg-top">
					<%= link_to "Edit Category", edit_category_path(category), class: "badge badge-primary badge-adjust" %>
					<%= link_to "Delete Category", category_path(category), method: :delete, 
						data: { confirm: "Are you sure you wish to Delete Category '" + category.name + "' ?"}, class: "badge badge-danger badge-adjust" %>
				</div>
			<% end %>
		</div>
	</div>
<% end %>
<div class="apple_pagination">
	<%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h2 class="action-heading">Create Category</h2>
<%= render 'form', message_type: "create" %>

app/views/categories/show.html.erb
<h2 class="action-heading center"><%= "Category: " + @category.name %></h2>
<% if logged_in? && current_user.admin? %>
	<div class="center">
		<%= link_to "Edit Category", edit_category_path(@category), class: "badge badge-primary badge-adjust" %>
		<%= link_to "Delete Category", category_path(@category), method: :delete, 
				data: { confirm: "Are you sure you wish to Delete this Category?"}, class: "badge badge-danger badge-adjust" %>
	</div>
<% end %>
<div class="apple_pagination">
	<%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', object: @category_articles %>
<div class="apple_pagination">
	<%= will_paginate @category_articles %>
</div>
<p><%= link_to "Return to Category Listing", categories_path %></p>

app/views/layouts/_footer.html.erb
<div class = "container"> 
  <footer class="footer">
    <small>
      Copyright &copy; 606AcademyLLC by Greg Wegrzynowicz
    </small>
      <nav>
        <ul>
          <li><%= link_to "About", about_path%>
          </li>
        </ul>
      </nav>
  </footer>

</div> 

app/views/layouts/_messages.html.erb
<% if flash.any? %>
	<% flash.each do |name, msg| %>
		<div class="container flash-adjust">
			<div class='alert alert-<%="#{name}"%> alert-dismissable fade show' role="alert">
				<%= msg %>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    			<span aria-hidden="true">&times;</span>
	  		  </button>
			</div>
		</div>
	<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-adjust">
  <%= link_to "606 Basketball Blog", root_path, class: "navbar-brand", id: "main-logo" %>
  <button class="navbar-toggler navbar-toggler-icon" id="navbar-menu-adjust" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Articles", articles_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Bloggers", users_path, class: "nav-link" %></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
      
        <div class="dropdown-menu dropdown-adjust" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
          
          <% if logged_in? && current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to "Create New Category", new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions <%= "Admin" if current_user.admin? %>
        </a>
        <div class="dropdown-menu dropdown-adjust" aria-labelledby="navbarDropdown">
          <%= link_to "Create New Article", new_article_path, class: "dropdown-item" %>
          <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Edit Your Profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Delete this User", user_path(current_user), method: :delete, data: { confirm: "Are you sure you wish to Delete this User and ALL their Articles?"}, class:  "dropdown-item"%>
				<div class="pad-top">
      </li>
        <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link nav-link-adjust" %>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "nav-link nav-link-adjust" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link nav-link-adjust" %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chicago Basketball Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  </head>

  <body>
  <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is the about page </h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron hero">
	<h1 class="display-4">606 Basketball Blog</h1>
	<p class="lead">Site for all discussions regarding basketball in the 606 Zipcode</p>
	<hr class="my-4">
	
	<%= link_to "Sign Up Now!", signup_path, class: "btn btn-primary btn-lg", role: "button" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger col-sm-8 offset-2" role="alert">
		<h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> occurred when trying to <%= message %> the <%= type %>:</h4>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user, message: message_type, type: "user" %>

<%= form_for @user do |f| %>
	<div class="form-group row">
		<div class="col-form-label col-sm-2">
			<%= f.label :username %>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-form-label col-sm-2">
			<%= f.label :email %>
		</div>
		<div class="col-sm-8">
			<%= f.email_field :email, class: "form-control", placeholder: "Enter Email Address" %>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-form-label col-sm-2">
			<%= f.label :password %>
		</div>
		<div class="col-sm-8">
			<%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
		</div>
	</div>

	<div class="form-group row">
		<div class="col-sm-12 center">
			<%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary btn-lg") %>
		</div>
	</div>
<% end %>
<p class="center"><%= link_to "Return to Article Listing", articles_path %></p>

app/views/users/edit.html.erb
<h2 class="action-heading center">Edit your Account</h2>
<%= render 'form', message_type: "edit" %>

app/views/users/index.html.erb
<h1 class="action-heading center">All 606 Bloggers and Ballers</h1>
<div class="apple_pagination">
	<%= will_paginate @users %>
</div>
<% @users.each do |user| %>
	<div class="card text-center card-adjust w-75 mx-auto">
		<div class="card-body">
			<p><%= link_to gravatar_for(user), user_path(user), class: "center" %></p>
			<h4><%= link_to user.username.gsub(/\w{2,}\b/) { |word| word.capitalize }, user_path(user), class: "center" %></h4>
			<div class="text-muted"><%= pluralize(user.articles.count, "article") if user.articles %></div>
			<% if (logged_in? and (current_user.admin? or current_user==user)) %>
				<div class="pad-top"><%= link_to "Delete this User", user_path(user), method: :delete, 
								data: { confirm: "Are you sure you wish to Delete this User and ALL their Articles?"}, class: "btn btn-sm btn-danger" %></div>
			<% end %>

		</div>
	</div>
<% end %>
<div class="apple_pagination">
	<%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h2 class="action-heading">Sign Up for the 606 Blog</h2>

<%= render 'form', message_type: "create" %>

app/views/users/show.html.erb
<h2 class="action-heading center"><%= "#{@user.username.gsub(/\w{2,}\b/) { |word| word.capitalize }}'s page" %></h2>
<div class="row">
	<div class="col center">
		<%= gravatar_for(@user, size: 150) %>
	</div>
</div>
<h4 class="action-heading center"><%= "#{@user.username.gsub(/\w{2,}\b/) { |word| word.capitalize }}'s Articles List" %></h4>
<div class="apple_pagination">
	<%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', object: @user_articles %>
<div class="apple_pagination">
	<%= will_paginate @user_articles %>
</div>